components/create/aliases.tsx, components/create/basic.tsx, components/create/createLoader.tsx, components/create/createStep.tsx, components/footer.tsx, components/import/aliases.tsx, components/import/basic.tsx, components/import/importLoader.tsx, components/import/importStep.tsx, components/modal.tsx, components/navbar.tsx, components/proposals.tsx, components/topUpForm.tsx, components/transferForm.tsx, context/formContext.ts, context/state.ts, pages/_app.tsx, pages/contracts.tsx, pages/contracts/[contract].tsx, pages/import.tsx, pages/index.tsx
Add import page to have the ability to import pre-existing wallets.
=> Add import page for wallets

components/create/createLoader.tsx, components/import/importLoader.tsx, components/modal.tsx, components/navbar.tsx, components/proposals.tsx, components/signersForm.tsx, context/state.ts, context/types.ts, context/unitContract.ts, pages/contracts/[contract].tsx, tsconfig.json
Add the form to have the ability to change the signers of the wallet/signers threshold
=> Form for changing signers/threshold

components/proposals.tsx, components/signersForm.tsx, components/topUpForm.tsx, components/transferForm.tsx, context/config.ts, context/state.ts, context/unitContract.ts, pages/contracts/[contract].tsx
- Update contract version
- Use views and events to make UI interactive
=> update contract version/add views

components/proposals.tsx, components/signersForm.tsx, components/topUpForm.tsx, components/transferForm.tsx, context/state.ts, pages/wallets/[wallet].tsx
- units of tez consistency
- updates to proposals,balance,signatures in proposals
- correctly display threshold, owners, signatures
- close the form on submission after a period of time
- loading indicators on sign/reject proposal
- correctly propagate updates for balance changes/signers/thresholds
=> more fixes

components/create/aliases.tsx, components/create/basic.tsx, components/import/aliases.tsx, components/import/basic.tsx, components/navbar.tsx, components/proposals.tsx, components/textInputWithComplete.tsx, components/topUpForm.tsx, components/transferForm.tsx, context/state.ts, pages/address-book.tsx, pages/create.tsx, pages/wallets/[wallet].tsx, utils/radixTrie.ts, versioned/interface.ts
-  add address-book
-  add completions when typing out an alias in [Create contract.aliases, wallet.create_proposal.transfer]
=> add address-book

context/metadata.ts, context/metadata_blob.ts, context/unitContract.ts, pages/create.tsx, types/009Proposal.ts, types/app.ts, types/display.ts, versioned/apis.ts, versioned/interface.ts, versioned/version009.ts
- add support for version 0.0.9
- create contracts on version 0.0.9
=> add version 0.0.9

context/metadata.ts, context/metadata_blob.ts, context/unitContract.ts, pages/create.tsx, types/009Proposal.ts, types/app.ts, types/display.ts, versioned/apis.ts, versioned/interface.ts, versioned/version009.ts
- add support for version 0.0.9
- create contracts on version 0.0.9
=> @zett98/009 version

components/footer.tsx, context/proposals.ts, pages/wallets/[wallet].tsx, versioned/apis.ts, versioned/interface.ts, versioned/version006.ts, versioned/version008.ts, versioned/version009.ts
=> @zett98/move to indexer

components/contractLoader.tsx, components/create/aliases.tsx, components/create/basic.tsx, components/create/createLoader.tsx, components/import/aliases.tsx, components/import/basic.tsx, components/import/importLoader.tsx, components/proposalSignForm.tsx, components/proposals.tsx, components/signersForm.tsx, context/formContext.ts, context/metadata.ts, context/metadata_blob.ts, context/unitContract.ts, pages/_app.tsx, pages/create.tsx, pages/wallets/[wallet].tsx, types/010Proposal.ts, types/display.ts, versioned/apis.ts, versioned/forms.ts, versioned/interface.ts, versioned/version006.ts, versioned/version009.ts, versioned/version010.ts
- Add support for version 0.0.10
- split signing the proposal and resolving it in the UI
=> add support for version 0.0.10

components/navbar.tsx, components/proposals.tsx, context/proposals.ts, context/state.ts, pages/_app.tsx, pages/address-book.tsx, pages/create.tsx, pages/import.tsx, pages/index.tsx, pages/wallets.tsx, pages/wallets/[wallet].tsx, types/display.ts
- fix navbar, footer and overflow of containers
- add favourite wallet functionality
- replace home page with favourite contract if one is present. 
- (By default if user doesn't have a favourite wallet, then the first originated/imported wallet is set as default)
=> UI-Fixes/add favourites

components/import/basic.tsx, pages/wallets/[wallet].tsx
- Fix address validation on import and wallet page
=> fix address validation

components/footer.tsx, components/navbar.tsx, pages/_app.tsx, pages/index.tsx, styles/globals.css
This PR updates the home to match the new UI
=> [Refactor] Home UI

components/contractLoader.tsx, components/create/aliases.tsx, components/create/basic.tsx, components/create/createLoader.tsx, components/create/createStep.tsx, components/footer.tsx, components/import/aliases.tsx, components/import/basic.tsx, components/import/importLoader.tsx, components/links.tsx, components/loginButton.tsx, components/navbar.tsx, components/proposalSignForm.tsx, components/proposals.tsx, components/signersForm.tsx, components/stepper.tsx, components/textInputWithComplete.tsx, components/topUpForm.tsx, components/transferForm.tsx, pages/address-book.tsx, pages/create.tsx, pages/import.tsx, pages/index.tsx, pages/wallets.tsx, pages/wallets/[wallet].tsx, tailwind.config.js, versioned/interface.ts
This PR mainly refactor the wallet creation UI, and includes some fixes as well. 
The main fix is the _gray fix_. Basically, for a reason that I don't know, the `gray` has been overridden in the tailwind config file, which causes all the gray colors to not work. As it can lead to unwanted behaviors, I removed the override value and replaced `gray` by `zinc` in classes, which is way more close of the colors that we use. 
The main changes are in files under `components/create/...`, and the rest is noises due to the fact that a lot of borders came back when fixing the gray color. I'm really sorry about it, this is the last time I'll have noise
https://user-images.githubusercontent.com/36401048/219331435-502012f3-d211-4c03-8cf2-9a5cb7ef33c3.mov
=> [Refactor] Create wallet UI

components/navbar.tsx
I'm not sure if I'm the one who broke the nav bar responsive or it was before, but anyway, here is a fix: 
https://user-images.githubusercontent.com/36401048/220556742-ea1366d2-9ecb-4ce5-9ee1-b1aa62d10566.mov
=> [Fix] Nav responsive

components/create/createLoader.tsx, context/config.ts, context/metadata_blob.ts, context/state.ts
=> add metadata on ipfs

.dockerignore, Dockerfile, components/loginButton.tsx, components/navbar.tsx, context/config.ts, context/proposals.ts, context/state.ts, pages/_app.tsx, pages/create.tsx, pages/import.tsx
code base supports env variable
=> [Feature] code base supports env variable

components/create/aliases.tsx, components/create/createLoader.tsx, components/import/aliases.tsx, components/import/basic.tsx, components/import/importLoader.tsx, components/import/importStep.tsx, components/signersForm.tsx, context/state.ts, next.config.js, pages/_app.tsx, pages/create.tsx, pages/import.tsx, pages/settings.tsx
This PR refactor the UI so it's matching the wallet creation, and it fixes aliases bugs
=> [Refactor] Wallet import

components/Sidebar.tsx, components/navbar.tsx, components/topUpForm.tsx, pages/create-proposal.tsx, pages/create.tsx, pages/import.tsx, pages/index.tsx, pages/settings.tsx, pages/top-up.tsx
- create new wallet -> new wallet
- create a proposal -> new proposal
- top up wallet -> fund wallet
- import existing wallet -> import wallet
- delete -> deleting in setting if canDelete is false
=> rename terms on UI

components/ProposalCard.tsx, components/Sidebar.tsx, components/signersForm.tsx, pages/new-proposal.tsx, pages/settings.tsx, utils/useIsOwner.ts
This PR disables `create proposal` and `settings` page if the user isn't the owner
=> [Fix] Limit user actions if not owner

components/create/aliases.tsx, components/import/aliases.tsx, components/signersForm.tsx, context/state.ts, utils/adaptiveTime.ts
This PR fixes the favorite contract and the proposal durations inputs:
- Now if you refresh you should have the same contract selected than before
- If you enter a wrong input you should have an error message
=> [Fix] Favorite and NaN

types/006Proposal.ts, types/008Proposal.ts, types/009Proposal.ts, types/010Proposal.ts, types/011Proposal.ts, versioned/version006.ts, versioned/version008.ts, versioned/version009.ts, versioned/version010.ts, versioned/version011.ts
A quick fix because there was a type issue preventing the build of the website, but the types were wrong so they needed to be updated
=> [Fix] Version number type

components/proposalSignForm.tsx, components/signersForm.tsx, components/transferForm.tsx, context/config.ts, utils/timeout.ts, versioned/interface.ts, versioned/version006.ts, versioned/version008.ts, versioned/version009.ts, versioned/version010.ts, versioned/version011.ts
As we still have an issue with taquito confirming if the transactions, I added a timeout so the user can have some feedback if we don't have confirmation. Is set the timeout to `90s`
=> [Fix] Handling timeout

components/import/aliases.tsx, components/signersForm.tsx, context/state.ts, pages/_app.tsx, pages/import-wallet.tsx
- show sidebar when signing out
- import wallet shouldn't require log in
=> while sign out, the imported wallets should be able show on UI 

components/transferForm.tsx, pages/history.tsx, versioned/apis.ts
Fix formatting of default entrypoint payload in contract if its type is unit
=> fix default entrypoint in lambda

components/signersForm.tsx, context/state.ts, pages/address-book.tsx
I thought I fixed a bug with the address book, but I actually introduced one when adding a new signer, it would erase all the aliases basically
=> [Fix] Prevent erasing all the aliases

components/transferForm.tsx, versioned/interface.ts
1. fix default value of lambda form
2. modify some terms
3. modify style
for the change 1 and 3, please see the snapshots:
before:
after:
=> [fix] proposal form

components/ProposalCard.tsx, components/transferForm.tsx
This PR updates the contract call UI. Basically, it adds margin and padding, and a new summary of contract call
=> [Refactor] Updated contract call UI

types/011Proposal.ts, versioned/version011.ts
The threshold was null if you tried to update it before
=> [Fix] Settings threshold

README.md
=> [Doc] Readme

components/ProposalCard.tsx, components/create/aliases.tsx, components/create/basic.tsx, components/import/basic.tsx, components/signersForm.tsx, components/topUpForm.tsx, components/transferForm.tsx, pages/index.tsx, pages/proposals.tsx, utils/adaptiveTime.ts, versioned/interface.ts
This PR fixes:
- Homepage wording
- Handles error messages for contract call and lambda parsing
- Show error when mutez amounts are `<= 0`
- Show the exact proposal duration time
- Show an error when importing a non TzSafe contract
- Detecting correctly FA2 transactions
=> [Fix] Small bugs

components/navbar.tsx, components/signersForm.tsx, pages/address-book.tsx, pages/fund-wallet.tsx, pages/history.tsx, pages/import-wallet.tsx, pages/index.tsx, pages/new-proposal.tsx, pages/new-wallet.tsx, pages/proposals.tsx, pages/settings.tsx, pages/wallets.tsx
=> [Fix] Pre-Release fix

components/Banner.tsx, pages/_app.tsx
This PR adds a banner to warn from fishing
=> [Feat] Fishing Banner

components/ProposalCard.tsx, components/transferForm.tsx, versioned/version011.ts
Another attempt at fixing more form errors
=> Fix form errors

README.md, script/Dockerfile.stateful, script/docker-compose.stateful.yml, script/docker-compose.stateless.yml
prepare sandbox of both tezos-node and tzkt's components
- docker-compose.stateless.yml: when containers is done, all the data will be gone
- docker-compose.stateful.yml: the data will remain.
=> [Feature] sandbox mode

.github/workflows/build_tzsafe.yml
ghostnet.tzsafe.marigold.dev is running on mannnet due to the wrong env on CI.
=> [fix] fix passing wrong env

components/ProposalCard.tsx, components/signersForm.tsx, components/transferForm.tsx, context/delegate.ts, context/state.ts, types/display.ts, versioned/forms.ts, versioned/version010.ts, versioned/version011.ts
This PR adds wallet delegation. To do so we have a field in the settings, and if it's filled, it means you want to delegate, and if you erase it, you'll "undelegate"
=> [Feature] Delegation

components/Alias.tsx
Currently, it's wrong string being displayed
=> [Fix] Alias component

components/ContractExecution.tsx, components/Sidebar.tsx, components/transferForm.tsx
This PR allows to keep a proposal state if the proposal creation fails. This way, the user can update what needs to be updated and submit another proposal
=> [Feature] Failed proposal keep state

Dockerfile, components/ContractExecution.tsx, components/ProposalCard.tsx, components/Sidebar.tsx, components/modal.tsx, components/proposals.tsx, components/topUpForm.tsx, components/transferForm.tsx, package-lock.json, package.json, pages/history.tsx, tests/tez.spec.ts, utils/tez.ts, versioned/interface.ts, versioned/version011.ts
This PR remove all mutez references and replace everything by Tez so it's easier for users.
There's one important question that needs to be answer tho: should we write `xtz` or `tez` everywhere?
There's also some small UI fixes in it
=> [Refactor] Mutez to Tez

components/proposalSignForm.tsx, versioned/interface.ts
This PR fixes #76 
Here is the new look:
=> [Refactor] Resolve proposal button

components/Alias.tsx, components/Autocomplete.tsx, components/Copy.tsx, components/FA2Transfer.tsx, components/Select.tsx, components/transferForm.tsx, context/config.ts, package-lock.json, package.json, pages/_app.tsx, styles/globals.css, versioned/interface.ts
This PR adds autocompletion to the FA2 fields, and improves UX, here are the changes:
- Searching for the FA2 tokens of the account
- Showing token id, contract, image if possible and token name
- Can't set an amount gt than the tokens balance
=> [Feature] FA2 autocomplete

context/parseLambda.ts, tests/decodeB58.spec.ts, utils/contractParam.ts
before:
after:
limit:
it won't decode `lamdba`. (leave it to future work)
=> [fix] decodeb58 certains type for contract execution

components/proposalSignForm.tsx
This PR add a warning before signing the proposal to make user is aware that this change will apply on all the proposals
=> [Fix] Warning when adding or removing signers

components/RenderTokenOption.tsx, components/Select.tsx, components/topUpForm.tsx, context/config.ts, pages/fund-wallet.tsx, styles/globals.css, utils/tez.ts
This PR allows to fund fa1.2 and fa2 tokens with a batch transaction
=> [Feat] fa1.2 and fa2 funding

components/ContractExecution.tsx, components/transferForm.tsx, utils/contractParam.ts
The amount was randomly kept or not, this version makes sure it's 100% kept when clicking continue
=> [Fix] Contract execution amount

components/footer.tsx, components/navbar.tsx
This PR adds network infos in nav, and a link in the footer
=> [Feat] Network infos

components/ProposalCard.tsx, components/RenderProposalContentLambda.tsx, components/proposalSignForm.tsx
the change:
- refactor to add warning message
- only show warning message when signing and resolving with approval result. the same change is applied to settings for the warning of the change. 
when sign the proposal:
when reject the proposal:
when resolve the proposal (approve):
when resolve the proposal (reject):
cc: @tj825
=> feature: show warning message to alert users when there is a lambda execution in a proposal

components/ProposalCard.tsx, components/RenderProposalContentLambda.tsx, components/proposalSignForm.tsx
- More warning message for the change of settings
- threshold is in human readable format
The warning message of `remove signer`:
The warning message of proposal update:
The warning message of "short" proposal duration:
=> feat: more warning message setting

components/navbar.tsx
Fixing this [issue](https://github.com/marigold-dev/tzsafe-issue/issues/32)
=> [Fix] Prevent alias from being too long on mobile

components/ProposalCard.tsx, components/Sidebar.tsx, pages/_app.tsx, pages/index.tsx
This PR disabled the sidebar links as long as Tzsafe is loading, so it avoids wrong redirection. It also fixes a an issue that redirected you to not imported wallet when navigating to `/`
=> [Fix] Sidebar link disabled

package-lock.json, package.json
the formkit version > 2.4.1 will cause a bug for using contractExecutoin.
The bug triggered by click adding item into array form.
```
Unhandled Runtime Error
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```
=> fix: downgrade formik

components/FA1_2.tsx, components/FA2Transfer.tsx, components/RenderProposalContentLambda.tsx, components/Sidebar.tsx, components/proposalSignForm.tsx, components/signersForm.tsx, components/topUpForm.tsx, context/config.ts, context/metadata.ts, context/metadata_blob.ts, context/proposals.ts, pages/[walletAddress]/history.tsx, pages/[walletAddress]/proposals.tsx, pages/_app.tsx, types/Proposal0_3_1.ts, utils/useWalletTokens.ts, versioned/interface.ts, versioned/version0_1_1.ts, versioned/version0_3_1.ts
This PR adds pagination for proposals and history, and it fixes `0.3.1` related bug as well
=> [Feat] Pagination for proposals and history

context/parseLambda.ts, tests/decodeB58.spec.ts, tests/lambdaParsing.spec.ts
bug: using wrong decoding to decode key_hash
change:
- fix decoding
- using real test data instead
- correct the description of test case and add more.
=> fix: fix decoding

components/proposalSignForm.tsx, pages/[walletAddress]/history.tsx, pages/[walletAddress]/proposals.tsx
The signers were only calculated for local wallets and not fetched ones
=> [Fix] Sign form signers

utils/contractParam.ts
use bignumber instead for handling precision
=> fix: use bignumber instead for handling precision

components/LoginModal.tsx, components/PoeModal.tsx, package-lock.json, pages/[walletAddress]/beacon.tsx, pages/_app.tsx
Beacon was still working, but a better redirection was needed, so here it is
=> [Fix] Handling beacon connection

components/LoginModal.tsx, components/PoeModal.tsx, pages/_app.tsx
Adding check for signers and if the user is login
=> [Fix] Login modal

context/config.ts, context/wert.ts, pages/[walletAddress]/fund-wallet.tsx
This PR adds the prod credentials for Wert
=> [Feat] Prepared wert for prod

components/Sidebar.tsx
This PR fixes the bug that Tezos Domains found about our rounding
=> fix(Sidebar): Fixed the Tez rouding and added the full amount on hover

pages/[walletAddress]/beacon.tsx, versioned/version0_1_1.ts, versioned/version0_3_0.ts, versioned/version0_3_1.ts, versioned/version0_3_2.ts, versioned/version0_3_3.ts
The submitted proposal from beacon is incorrect unit.
=> fix: do not convert mutez for the request from beacon

pages/[walletAddress]/proposals.tsx
=> fix(App): Forcing refresh on global refresher

components/LoginModal.tsx, components/PoeModal.tsx
=> [fix] modify wording and fix the version for the connection

components/PoeModal.tsx, components/ProposalCard.tsx, dapps/index.ts, dapps/objkt.tsx, dapps/tezosDomains.tsx
=> [Fix] Added title and aligned buttons and columns in Poe Modal

components/PoeModal.tsx, context/state.ts, versioned/version0_3_0.ts, versioned/version0_3_1.ts, versioned/version0_3_2.ts
Removed dead code in the `PoeModal` and the state as well.
Also some of the version files has been formatted
=> clean: Removing dead code and formatted code

components/PoeModal.tsx, context/P2PClient.ts
Only accepting if the transaction is completed
=> refactor(Poe): Moved the accepted after the transaction

components/PoeModal.tsx, components/transferForm.tsx, tests/e2eTest/v0.1.1.ts, tests/e2eTest/v0.3.3.ts, tests/e2eTest/v0.3.4.ts, versioned/interface.ts, versioned/version0_0_10.ts, versioned/version0_0_11.ts, versioned/version0_0_6.ts, versioned/version0_0_8.ts, versioned/version0_0_9.ts, versioned/version0_1_1.ts, versioned/version0_3_0.ts, versioned/version0_3_1.ts, versioned/version0_3_2.ts, versioned/version0_3_3.ts, versioned/version0_3_4.ts
https://github.com/marigold-dev/tzsafe-ui/issues/150
Creating a proposal with 1 threshold:
Creating a proposal with a threshold greater than one:
Incoming action with 1 threshold:
Incoming action with a threshold greater than one:
Message signing with 1 threshold:
Message signing with a threshold greater than one:
=> Signing and resolving proposal together with creating proposal

components/dashboard/balance.tsx
The minus sign appears two times
=> dashboard/balance: remove minus sign

context/state.ts
Linked to https://github.com/marigold-dev/tzsafe-ui/issues/175
=> Local storage per user
